name: Docker Todo-List CI

# The trigger: runs whenever there is a push to the main (or master) branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    # Virtual machine that GitHub will use (Ubuntu already comes with Docker)
    runs-on: ubuntu-latest

    steps:
      # 1. Download the code from your repository to the GitHub machine.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build and mount containers in detached mode (-d)
      # Get on the bench and the API first
      - name: Build and Spin up Docker
        run: docker-compose up -d db api

      # 3. Wait for the database to be ready
      # Mongo takes a few seconds to accept connections
      - name: Wait for services to be ready
        run: sleep 15

      # 4. Runs the test container we configured in docker-compose
      # --exit-code-from ensures that if the test fails, GitHub notifies you.
      - name: Run Tests
        run: docker-compose run --rm tests

      # 5. It is optional, but we clean up so as not to leave any traces.
      - name: Shutdown Docker
        if: always()
        run: docker-compose down